server:
  port: 80
spring:
  datasource:
    primary.connection-timeout: 300000
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
#    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:h2test
    username: root
    password: test
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

management:
  shutdown:
    whitelist: 0.0.0.0
  server:
    port: 13654
  endpoints:
    web:
      base-path: /folaqwedd
      exposure:
        include: "*"
  endpoint:
    health.show-details: always
    shutdown.enabled: true
